package perpustakaandigital;

import Config.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

public class halPinjamBuku extends javax.swing.JFrame {
    
    Connection conn;

    public halPinjamBuku() {
        initComponents();

        conn = new koneksi().getConnection();

        for (var listener : btnPinjam.getActionListeners()) {
            btnPinjam.removeActionListener(listener);
        }
        btnPinjam.addActionListener(evt -> simpanPeminjaman());
    }

    private void simpanPeminjaman() {
        String kodeBuku = tfKodeBuku.getText().trim();
        String judulBuku = tfJudulBuku.getText().trim();
        String penulis = tfPenulis.getText().trim();
        String tanggalPinjam = tfTanggalPinjam.getText().trim();
        String waktuPinjam = tfWaktuPinjam.getText().trim();

        // Validasi input
        if (kodeBuku.isEmpty() || judulBuku.isEmpty() || penulis.isEmpty() || tanggalPinjam.isEmpty() || waktuPinjam.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi format tanggal
        java.sql.Date sqlTanggalPinjam;
        try {
            java.util.Date parsedDate = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggalPinjam);
            sqlTanggalPinjam = new java.sql.Date(parsedDate.getTime());
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi format waktu
        if (!waktuPinjam.matches("\\d{2}:\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Format waktu harus HH:mm.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cek apakah buku ada di tabel "buku"
        String cekBukuSql = "SELECT COUNT(*) FROM buku WHERE Kode_buku = ? AND Judul = ? AND Penulis = ?";
        try (PreparedStatement cekStmt = conn.prepareStatement(cekBukuSql)) {
            cekStmt.setString(1, kodeBuku);
            cekStmt.setString(2, judulBuku);
            cekStmt.setString(3, penulis);
            try (ResultSet rs = cekStmt.executeQuery()) {
                if (rs.next() && rs.getInt(1) == 0) {
                    JOptionPane.showMessageDialog(this, "Buku tidak ditemukan di database. Tidak dapat dipinjam.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat memeriksa data buku: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cek apakah buku sudah dipinjam
        String cekPinjamSql = "SELECT COUNT(*) FROM buku_pinjam WHERE Kode_buku = ?";
        try (PreparedStatement cekPinjamStmt = conn.prepareStatement(cekPinjamSql)) {
            cekPinjamStmt.setString(1, kodeBuku);
            try (ResultSet rs = cekPinjamStmt.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(this, "Buku \"" + judulBuku + "\" sudah dipinjam.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat memeriksa data pinjaman: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Simpan data ke tabel "buku_pinjam"
        String sql = "INSERT INTO buku_pinjam (Kode_buku, Judul, Penulis, Tanggal_pinjam, Waktu_pinjam) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, kodeBuku);
            pstmt.setString(2, judulBuku);
            pstmt.setString(3, penulis);
            pstmt.setDate(4, sqlTanggalPinjam);
            pstmt.setString(5, waktuPinjam);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Buku \"" + judulBuku + "\" telah dipinjam.", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

            resetForm();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat menyimpan data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetForm() {
        tfKodeBuku.setText("");
        tfJudulBuku.setText("");
        tfPenulis.setText("");
        tfTanggalPinjam.setText("");
        tfWaktuPinjam.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfKodeBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfJudulBuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfWaktuPinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTanggalPinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPenulis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("PINJAM BUKU");
        jPanel2.add(jLabel6, new java.awt.GridBagConstraints());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        tfKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeBukuActionPerformed(evt);
            }
        });
        jPanel1.add(tfKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 290, -1));

        jLabel2.setText("Judul Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        tfJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJudulBukuActionPerformed(evt);
            }
        });
        jPanel1.add(tfJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 290, -1));

        jLabel3.setText("Penulis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        tfWaktuPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWaktuPinjamActionPerformed(evt);
            }
        });
        jPanel1.add(tfWaktuPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, -1));

        jLabel4.setText("HH:MM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 70, 20));

        tfTanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalPinjamActionPerformed(evt);
            }
        });
        jPanel1.add(tfTanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, -1));

        jLabel5.setText("Tanggaal Peminjaman");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel7.setText("Waktu Peminjaman");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        tfPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPenulisActionPerformed(evt);
            }
        });
        jPanel1.add(tfPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, -1));

        jLabel8.setText("YYYY-MM-DD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, 20));

        btnPinjam.setText("Selesai");
        btnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPinjam))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPinjam)
                        .addComponent(jButton1))
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        // TODO add your handling code here:
        simpanPeminjaman();
    }//GEN-LAST:event_btnPinjamActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalPinjamActionPerformed

    private void tfWaktuPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWaktuPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWaktuPinjamActionPerformed

    private void tfJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJudulBukuActionPerformed

    private void tfKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeBukuActionPerformed

    private void tfPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPenulisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tfJudulBuku;
    private javax.swing.JTextField tfKodeBuku;
    private javax.swing.JTextField tfPenulis;
    private javax.swing.JTextField tfTanggalPinjam;
    private javax.swing.JTextField tfWaktuPinjam;
    // End of variables declaration//GEN-END:variables
}
